### ISSUE TITLE
Can you share WikiANN - NER Chinese data?

### ISSUE THREAD

**Issue by edchengg** [shijie-wu/crosslingual-nlp#3]
Hi, I noticed in the paper (https://arxiv.org/pdf/2109.06798.pdf)
- there are some modification to the Chinese NER data

"As the supervision for Chinese NER is character-level,
we segment the characters into words using the
Stanford Word Segmenter and realign the label."

Do you mind share the data? I am trying to use it as a reference but currently failed to reproduce the results on Chinese.

Thanks!

**Comment by shijie-wu** [comment]
Email me sjwu at hey dot com. I can send you a copy.
